[config]
default-prelude = "pyenv"

[ubuntu]
required-repositories = ["ppa:deadsnakes/ppa"]
required-packages = [
    "build-essential", "pkg-config", "lld", "curl",
    "openssl", "libssl-dev", "liblzma-dev",
    "python3.11", "python3.11-venv", "python3.11-dev"
]

[preludes]
pyenv = "Sets up (if needed) and enables the python enviornment"

[targets]
install-pymongo = []
install-mongodb = []

[targets.run-mongod]
about = "Runs the monogdb server processs"
arguments = []

[targets.build-mongodb]
about = "Build MongoDB from source"
arguments = [{name="build-profile", default="default"}, {name="force-rebuild", default=0}]

[targets.prepare-data]
about = "Sets up the data needed to run experiments"
arguments = [{ name="server-address"}, { name="num-entries", default=1000 }]

[targets.client-ops]
about = "Issues client operations"
arguments = [
    { name="server-address" },
    { name="num-entries", default=1000 },
    { name="client-multiply", default=8},
    { name="num-operations", default=10000},
    { name="write-chance", default=50 }
]
